name: ci-node-workflow
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn test -- --coverage
